apiVersion: apps/v1
kind: Deployment
metadata:
  name: any-deployment
spec:
  template:
    spec:
      containers:
        - name: any-container
          image: any-image
          env:
            - name: ENV_VAR
              value: "original-value"
          # - name: ENV_VAR2
          #   valueFrom:
          #     secretKeyRef:
          #       name: xx-cred
          #       key: password
