apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources can be added as files or directories
resources:
  - api/
  - db/

# Common labels can be added to all resources
commonLabels:
  department: demo

# Namespace can be set for all resources
namespace: demo

# Name prefix and suffix can be used to modify the names of all resources
namePrefix: KAPPEL.TECH-

# Common annotations can be added to all resources
commonAnnotations:
  owner: Dennis Kappel
  project: demo
  description: Demo application

# (INLINE) Patches can be used to modify resources without changing the original files
patches:
  - target: 
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
